permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: |
          pip install --upgrade pip build twine keyring keyrings.google-artifactregistry-auth
          python -m build
          twine upload --non-interactive \
            --repository-url "https://${{ vars.GAR_REGION }}-python.pkg.dev/${{ vars.GCP_PROJECT }}/${{ vars.GAR_REPO }}/" \
            dist/*
